server:
  port: 8080
  servlet:
    context-path: /puzikov
spring:
  datasource:
    initialization-mode: never
    platform: h2
    url: jdbc:h2:file:./src/main/resources/db/movies;AUTO_SERVER=true;INIT=CREATE SCHEMA IF NOT EXISTS calendar
  session:
    jdbc:
        initialize-schema: never
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: on
    properties:
      hibernate:
#        globally_quoted_identifiers: true
        hbm2ddl:
          import_files: import.sql
        format_sql: true
