server:
    port: 8081
    servlet:
        context-path: /puzikov
spring:
    datasource:
        initialization-mode: always
        url: jdbc:h2:file:./src/main/resources/db/movies
        platform: h2
    session:
      jdbc:
          initialize-schema: always
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: on
